import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomCursor from "./components/CustomCursor";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-landing-grey ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <CustomCursor /> */}
        <div className="grid relative grid-cols-3">
          <div className="mt-10 ml-10  col-span-1">
            <div className=" fixed  text-landing-white col-span-1 grid grid-cols-1 grid-rows-10 h-96">
              <h1 className=" font-bold text-3xl tracking-wider">
                Isaac Martínez
              </h1>
              <h2 className=" uppercase tracking-normal text-lg pt-1">
                Front End Developer
              </h2>
              <div className="  row-span-8 text-landing-neon mt-20">
                <div className=" grid grid-cols-6 mb-2">
                  <div className=" col-span-3 border-t-2 border-landing-neon mt-2.5 w-20 ml-16"></div>
                  <span className=" col-span-3 uppercase ">about</span>
                </div>
                <div className=" grid grid-cols-6 mb-2">
                  <div className=" col-span-3 border-t-2 border-landing-neon mt-2.5 w-20 ml-16"></div>
                  <span className=" col-span-3 uppercase">Experience</span>
                </div>
                <div className=" grid grid-cols-6 mb-2">
                  <div className=" col-span-3 border-t-2 border-landing-neon mt-2.5 w-20 ml-16"></div>
                  <span className=" col-span-3 uppercase">Projects</span>
                </div>
              </div>
              <div className=" row-span-2">
                <h1>icons</h1>
              </div>
            </div>
          </div>
          <div className=" col-span-2">{children}</div>
        </div>
      </body>
    </html>
  );
}
