import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import CustomCursor from "./components/CustomCursor";
import SideBar from "./components/SideBar";
import { jobs, sections } from "./data/db";
import SectionCard from "./components/SectionCard";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`bg-landing-grey ${montserrat.className} antialiased`}>
        {/* <CustomCursor /> */}
        <div className="grid grid-cols-3">
          <SideBar />
          <div className=" col-span-2">{children}</div>
        </div>
      </body>
    </html>
  );
}
