import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import SideBar from "./components/SideBar";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`bg-landing-grey cursor-default ${montserrat.className} antialiased min-h-screen h-full`}
      >
        {/* <CustomCursor /> */}
        <div className="grid grid-cols-3 h-full">
          <SideBar />
          <main className="col-span-2 h-full scroller">{children}</main>
        </div>
      </body>
    </html>
  );
}
